"""Export NEC tables, code references and bilingual text from the Python
package to ``necalc_data.js`` so the web version uses the same data.

Run after changing necalc/tables.py, codes.py or i18n.py:
    python web/build_data.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))

from necalc import tables as T, codes, i18n, loads, tray  # noqa: E402

NAMES = [
    "SIZES", "CMIL", "AMPACITY_CU", "AMPACITY_AL", "TEMP_COLUMNS",
    "SMALL_CONDUCTOR_MAX_OCPD", "TEMP_CORRECTION", "CCC_ADJUSTMENT",
    "STANDARD_OCPD", "STANDARD_SWITCH", "MV_FUSE_E_RATINGS", "EGC_TABLE",
    "WIRE_AREA", "INSULATION_TEMP", "TRADE_SIZES", "CONDUIT_AREA",
    "FILL_PERCENT", "FILL_PERCENT_OVER_2", "TABLE9", "MOTOR_HP", "FLC_1PH",
    "FLC_1PH_VOLTS", "FLC_3PH", "FLC_3PH_VOLTS", "MOTOR_VOLT_MAP",
    "MOTOR_OCPD_PERCENT", "MOTOR_OCPD_PERCENT_DESIGN_B_EE_INST", "MV_SIZES",
    "MV_AMPACITY_TYPICAL", "MV_CABLE_OD_TYPICAL", "MV_MIN_SIZE", "SC_CONST",
    "XFMR_KVA_3PH", "XFMR_KVA_1PH", "AMPACITY_FREE_AIR_CU",
    "AMPACITY_FREE_AIR_AL", "TRAY_WIDTHS", "TRAY_DEPTHS", "TRAY_TYPES",
    "TRAY_A_COL1", "TRAY_A_COL2_K", "TRAY_A_COL3", "TRAY_A_COL4_K",
    "TRAY_SOLID_LARGE_PCT", "TRAY_CONTROL_PCT", "TRAY_B_COL1",
    "TRAY_B_COL2_K", "TRAY_AMP_LV_MULTI_COVERED", "TRAY_AMP_LV_SINGLE",
    "TRAY_AMP_MV_SINGLE", "TRAY_AMP_MV_MULTI_COVERED", "TC_3C_OD_TYPICAL",
    "TC_4C_OD_FACTOR", "MV_AMPACITY_AIR_TYPICAL", "MV_3C_OD_FACTOR",
    "MV_3C_JACKET_IN",
]


def conv(v):
    """JSON-friendly copy: tuple keys joined with '|', other keys str()."""
    if isinstance(v, dict):
        return {("|".join(k) if isinstance(k, tuple) else str(k)): conv(x)
                for k, x in v.items()}
    if isinstance(v, (list, tuple)):
        return [conv(x) for x in v]
    return v


def build():
    data = {
        "tables": {n: conv(getattr(T, n)) for n in NAMES},
        "XFMR_450_3A": conv(T.XFMR_450_3A),
        "refs": codes.REFS,
        "editions": list(codes.EDITIONS),
        "text": {k: list(v) for k, v in i18n.TEXT.items()},
        "categories": list(loads.CATEGORIES),
        "units": list(loads.UNITS),
        "phase_conn": list(loads.PHASE_CONN),
        "systems": {k: list(v) for k, v in loads.SYSTEMS.items()},
        "system_order": list(loads.SYSTEMS),
        "tray_kinds": list(tray.KINDS),
        "tray_arrangements": list(tray.ARRANGEMENTS),
    }
    js = ("/* Generated by web/build_data.py from the necalc Python package."
          " Do not edit. */\n(function (root) {\n  var DATA = " +
          json.dumps(data, ensure_ascii=False, separators=(",", ":")) +
          ";\n  if (typeof module !== 'undefined' && module.exports) "
          "module.exports = DATA;\n  else root.NECALC_DATA = DATA;\n})"
          "(typeof self !== 'undefined' ? self : this);\n")
    out = os.path.join(HERE, "necalc_data.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(js)
    return out


if __name__ == "__main__":
    print("wrote", build())
